name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker Image
        run: |
          docker build -t aws-devops-api .

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/aws-devops-deployment

            git pull origin main

            sudo docker stop flask-api || true
            sudo docker rm flask-api || true

            sudo docker build -t aws-devops-api .

            sudo docker run -d \
              --restart always \
              --name flask-api \
              -p 5000:5000 \
              aws-devops-api

            sudo systemctl restart nginx
